
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/checkin
      - VITE_SMTP_HOST=smtp.example.com
      - VITE_SMTP_PORT=587
      - VITE_SMTP_USER=user
      - VITE_SMTP_PASS=password
      - VITE_SMTP_FROM=no-reply@example.com
      - VITE_SMTP_TO=admin@example.com
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=checkin

volumes:
  mongo_data:
