
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/checkin
      - VITE_SMTP_HOST=smtp.example.com
      - VITE_SMTP_PORT=587
      - VITE_SMTP_USER=user
      - VITE_SMTP_PASS=password
      - VITE_SMTP_FROM=no-reply@example.com
      - VITE_SMTP_TO=admin@example.com
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
