
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VITE_MONGODB_URI=mongodb://mongodb:27017/checkin
      - VITE_SMTP_HOST=smtp.example.com
      - VITE_SMTP_PORT=587
      - VITE_SMTP_USER=user
      - VITE_SMTP_PASS=password
      - VITE_SMTP_FROM=no-reply@example.com
      - VITE_SMTP_TO=admin@example.com
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
