
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_SMTP_HOST=smtp.example.com
      - VITE_SMTP_PORT=587
      - VITE_SMTP_USER=user
      - VITE_SMTP_PASS=password
      - VITE_SMTP_FROM=no-reply@example.com
      - VITE_SMTP_TO=admin@example.com
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
    driver: local
