version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Grundlegende Konfiguration
      - NODE_ENV=production
      - PORT=3000
      
      # Umgebungsvariablen für Vite
      - VITE_ADMIN_USERNAME=admin
      - VITE_ADMIN_PASSWORD=admin
      - VITE_DB_HOST=mysql
      - VITE_DB_PORT=3306
      - VITE_DB_USER=checkin
      - VITE_DB_PASSWORD=checkin
      - VITE_DB_NAME=checkin_db
      
      # SMTP-Konfiguration für E-Mail-Versand
      - VITE_SMTP_HOST=smtp.example.com
      - VITE_SMTP_PORT=587
      - VITE_SMTP_USER=user@example.com
      - VITE_SMTP_PASS=yourpassword
      - VITE_SMTP_FROM=noreply@example.com
      - VITE_SMTP_TO=recipient@example.com
      - VITE_SMTP_SUBJECT="Neuer Besucher Check-In"
      
      # Datenbank-Konfiguration (für Server-Seite)
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=checkin
      - DB_PASSWORD=checkin
      - DB_NAME=checkin_db
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.3
    command: --authentication-policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --set-variable host_cache_size=0 --ssl=0 --disable-ssl
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=checkin_db
      - MYSQL_USER=checkin
      - MYSQL_PASSWORD=checkin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "checkin", "-pcheckin", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
