
name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        # Selbst wenn keine Secrets gesetzt sind, bauen wir das Image trotzdem
        # aber überspringen den Login- und Push-Schritt bei fehlenden Credentials
        username: ${{ secrets.DOCKERHUB_USERNAME || '' }}
        password: ${{ secrets.DOCKERHUB_TOKEN || '' }}
        # Überspringen, wenn keine Credentials vorhanden sind
        registry: docker.io
      continue-on-error: true
        
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        # Nur pushen, wenn wir Credentials haben und es kein Pull Request ist
        push: ${{ github.event_name != 'pull_request' && secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME || 'local' }}/checkin-system:latest
        platforms: linux/amd64,linux/arm64
        # Nur Cache verwenden, wenn wir Credentials haben
        cache-from: ${{ secrets.DOCKERHUB_USERNAME != '' && format('type=registry,ref={0}/checkin-system:buildcache', secrets.DOCKERHUB_USERNAME) || '' }}
        cache-to: ${{ secrets.DOCKERHUB_USERNAME != '' && format('type=registry,ref={0}/checkin-system:buildcache,mode=max', secrets.DOCKERHUB_USERNAME) || '' }}
